*--------------------------------------------------------------------------------------------------*
* TABELA SEUNI.SPP_BENEFICIARIO																	   *
*--------------------------------------------------------------------------------------------------*

CREATE TABLE "SEUNI"."SPP_BENEFICIARIO" ("ID" NUMBER NOT NULL, 
    "CD_UNIDADE_CARTEIRA" NUMBER NOT NULL, "CD_CARTEIRA" NUMBER 
    NOT NULL, "PARTO_TIPO" CHAR(7 byte), "PARTO_PESO_NASCIMENTO" 
    NUMBER, "PARTO_ESTATURA_NASCIMENTO" NUMBER, 
    "PARTO_P_CEFALICO_NASCIMENTO" NUMBER, "PARTO_CD_CID" 
    VARCHAR2(4 byte), "MENARCA" VARCHAR2(5 byte), "MENARCA_DATA" 
    DATE, "DATA_INCLUSAO" DATE NOT NULL, "DATA_ATUALIZACAO" DATE 
    NOT NULL, "USUARIO_INCLUSAO" NUMBER NOT NULL, 
    "USUARIO_ATUALIZACAO" NUMBER NOT NULL, "TRIAGEM_TESTE_OLHO" 
    VARCHAR2(5 byte), "TRIAGEM_TESTE_PE" VARCHAR2(5 byte), 
    "TRIAGEM_TESTE_ORELHA" VARCHAR2(5 byte), 
    "TRIAGEM_TESTE_CORACAO" VARCHAR2(5 byte), "PARTO_INTERNACAO" 
    VARCHAR2(5 byte), 
    CONSTRAINT "SPP_BENEFICIARIO_PK" UNIQUE("ID") 
    USING INDEX  
    TABLESPACE "TSIND_SERIOUS" 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
    TABLESPACE "TS_SERIOUS" PCTFREE 10 PCTUSED 0 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 
    MONITORING;

*--------------------------------------------------------------------------------------------------*
* TABELA SEUNI.SPP_BENEFICIARIO_CONSULTA														   *
*--------------------------------------------------------------------------------------------------*
CREATE TABLE "SEUNI"."SPP_BENEFICIARIO_CONSULTA" ("ID" NUMBER NOT
    NULL, "ID_SPP_BENEFICIARIO" NUMBER NOT NULL, 
    "CD_UNIDADE_EXECUTANTE" NUMBER NOT NULL, 
    "CD_PRESTADOR_EXECUTANTE" NUMBER NOT NULL, "CD_PROCEDIMENTO" 
    NUMBER NOT NULL, "DT_REALIZACAO" DATE NOT NULL, 
    "ANTROPOMETRICO_PESO" NUMBER(5, 2), "ANTROPOMETRICO_ESTATURA"
    NUMBER, "ANTROPOMETRICO_P_CEFALICO" NUMBER, 
    "ANTROPOMETRICO_P_ARTERIAL_MAX" NUMBER(3), 
    "ANTROPOMETRICO_IMC" NUMBER, "TIPO_ALIMENTACAO" VARCHAR2(40 
    byte), "TIPO_ALIMENTACAO_OBSERVACAO" VARCHAR2(500 byte), 
    "ESTADO_NUTRICIONAL" VARCHAR2(20 byte), 
    "DENVER_BRUCOS_ERGUE_CABECA" VARCHAR2(5 byte), 
    "DENVER_FIXA_ROSTO_MAE" VARCHAR2(5 byte), 
    "DENVER_SORISSO_SOCIAL" VARCHAR2(5 byte), 
    "DENVER_MAOS_ABERTAS" VARCHAR2(5 byte), "DENVER_BALBUCIA" 
    VARCHAR2(5 byte), "DENVER_LEVA_OBJETOS_BOCA" VARCHAR2(5 byte),
    "DENVER_VIRA_CABECA_DIRECAO_SOM" VARCHAR2(5 byte), 
    "DENVER_OLHA_OBJETOS" VARCHAR2(5 byte), 
    "DENVER_GOSTA_BRINCAR" VARCHAR2(5 byte), 
    "DENVER_SENTA_SOZINHA" VARCHAR2(5 byte), 
    "DENVER_ARRASTA_ENGATINHA" VARCHAR2(5 byte), 
    "DENVER_FAZ_IMITACOES" VARCHAR2(5 byte), 
    "DENVER_ENGATINHA_ANDA_APOIO" VARCHAR2(5 byte), 
    "DENVER_FALA_ALGUMAS_PALAVRAS" VARCHAR2(5 byte), 
    "DENVER_ANDA_SOZINHO" VARCHAR2(5 byte), 
    "DENVER_COMPANHIA_CRIANCA" VARCHAR2(5 byte), 
    "DENVER_CORRE_SOBE_DEGRAUS" VARCHAR2(5 byte), 
    "DENVER_USA_PLURAIS" VARCHAR2(5 byte), 
    "DENVER_POE_SAPATO_SOZINHO" VARCHAR2(5 byte), 
    "DENVER_VESTE_SOB_SUPERVISAO" VARCHAR2(5 byte), 
    "DENVER_RECONHECE_CORES" VARCHAR2(5 byte), "DENVER_COPIA" 
    VARCHAR2(5 byte), "DENVER_DESENHA_HOMEM_6_PARTES" VARCHAR2(5 
    byte), "ATIVIDADE_FISICA" VARCHAR2(5 byte), 
    "ATIVIDADE_FISICA_QTDE_VEZES" NUMBER, 
    "DESENV_NEUROPSICOMOTOR" VARCHAR2(10 byte), 
    "DESENV_NEUROPSICOMOTOR_OBS" VARCHAR2(500 byte), 
    "ESCALA_TANNER_A" NUMBER, "ESCALA_TANNER_B" NUMBER, 
    "ESCALA_TANNER_C" NUMBER, "ESCOLARIDADE" VARCHAR2(15 byte), 
    "ATIVIDADE_FISICA_QTDE_MINUTOS" VARCHAR2(4 byte), 
    "ANTROPOMETRICO_P_ARTERIAL_MIN" NUMBER(3), 
    "TIPO_ALIMENTACAO_LEITE_MATERNO" VARCHAR2(5 byte), 
    "INTERCORRENCIA_1" VARCHAR2(5 byte), "INTERCORRENCIA_2" 
    VARCHAR2(5 byte), "INTERCORRENCIA_3" VARCHAR2(5 byte), 
    "INTERCORRENCIA_1_CD_CID" VARCHAR2(4 byte), 
    "INTERCORRENCIA_2_CD_CID" VARCHAR2(4 byte), 
    "INTERCORRENCIA_3_CD_CID" VARCHAR2(4 byte), 
    CONSTRAINT "SPP_BENEFICIARIO_CONSULTA_PK" UNIQUE("ID") 
    USING INDEX  
    TABLESPACE "TSIND_SERIOUS" 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
    TABLESPACE "TS_SERIOUS" PCTFREE 10 PCTUSED 0 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 
    MONITORING;

*--------------------------------------------------------------------------------------------------*
* TABELA SEUNI.SPP_BENEFICIARIO_VACINA															   *
*--------------------------------------------------------------------------------------------------*
CREATE TABLE "SEUNI"."SPP_BENEFICIARIO_VACINA" ("ID" NUMBER NOT 
    NULL, "ID_SPP_BENEFICIARIO" NUMBER NOT NULL, "NASCIMENTO_BCG"
    VARCHAR2(5 byte), "NASCIMENTO_HEPATITE_B" VARCHAR2(5 byte), 
    "M2_PNEUMOCOCICA_CONJUGADA" VARCHAR2(5 byte), "M2_DPT" 
    VARCHAR2(5 byte), "M2_POLIO" VARCHAR2(5 byte), "M2_HIB" 
    VARCHAR2(5 byte), "M2_ROTAVIRUS" VARCHAR2(5 byte), 
    "M2_HEPATTTE_B" VARCHAR2(5 byte), 
    "M3_MENINGOCOCICA_CONJUGADA" VARCHAR2(5 byte), 
    "M4_PNEUMOCOCICA_CONJUGADA" VARCHAR2(5 byte), "M4_DPT" 
    VARCHAR2(5 byte), "M4_POLIO" VARCHAR2(5 byte), "M4_HIB" 
    VARCHAR2(5 byte), "M4_ROTAVIRUS" VARCHAR2(5 byte), 
    "M5_MENINGOCOCICA_CONJUGADA" VARCHAR2(5 byte), 
    "M6_PNEUMOCICICA_CONJUGADA" VARCHAR2(5 byte), "M6_DPT" 
    VARCHAR2(5 byte), "M6_POLIO" VARCHAR2(5 byte), "M6_HIB" 
    VARCHAR2(5 byte), "M6_INFLUENZA" VARCHAR2(5 byte), 
    "M6_HEPATITE_B" VARCHAR2(5 byte), "M6_ROTAVIRUS" VARCHAR2(5 
    byte), "M7_INFLUENZA" VARCHAR2(5 byte), "M9_FEBRE_AMARELA" 
    VARCHAR2(5 byte), "M12_PNEUMOCOCICA_CONJUGADA" VARCHAR2(5 
    byte), "M12_TRIVIRAL" VARCHAR2(5 byte), "M12_HEPATITE_A" 
    VARCHAR2(5 byte), "M12_VARICELA" VARCHAR2(5 byte), 
    "M15_MENINGOCOCICA_C" VARCHAR2(5 byte), "M15_DPT" VARCHAR2(5 
    byte), "M15_POLIO" VARCHAR2(5 byte), "M15_HIB" VARCHAR2(5 
    byte), "M15_VARICELA" VARCHAR2(5 byte), "M15_TRIVIRAL" 
    VARCHAR2(5 byte), "M18_HEPATITE_A" VARCHAR2(5 byte), 
    "A2_INFLUENZAE" VARCHAR2(5 byte), "A3_INFLUENZAE" VARCHAR2(5 
    byte), "A4_INFLUENZAE" VARCHAR2(5 byte), 
    "A4_5_MENINGOCOCICA_CONJUGADA" VARCHAR2(5 byte), "A4_5_DPT" 
    VARCHAR2(5 byte), "A4_5_POLIO" VARCHAR2(5 byte), 
    "A4_5_INFLUENZAE" VARCHAR2(5 byte), 
    "A5_6_MENINGOCOCICA_CONJUGADA" VARCHAR2(5 byte), "A9_1HPV" 
    VARCHAR2(5 byte), "A9_2HPV" VARCHAR2(5 byte), "A9_3HPV" 
    VARCHAR2(5 byte), "A11_MENINGOCOCICA_CONJUGADA" VARCHAR2(5 
    byte), "A14_DT_DPT_ADULTO" VARCHAR2(5 byte), 
    "MEQ1A_MENINGO_B_RECOMB_1DOSE" VARCHAR2(5 byte), 
    "MEQ1A_MENINGO_B_RECOMB_2DOSE" VARCHAR2(5 byte), 
    "MEQ1A_MENINGO_B_RECOMB_3DOSE" VARCHAR2(5 byte), 
    "MEQ1A_MENINGO_B_RECOMB_REFORCO" VARCHAR2(5 byte), 
    "MAQ1A_MENINGO_B_RECOMB_1DOSE" VARCHAR2(5 byte), 
    "MAQ1A_MENINGO_B_RECOMB_2DOSE" VARCHAR2(5 byte), 
    "A0_4_MENINGO_TETRA_ACWY" VARCHAR2(5 byte), 
    "A5_19_MENINGO_B_RECOMB_1DOSE" VARCHAR2(5 byte), 
    "A5_19_MENINGO_B_RECOMB_2DOSE" VARCHAR2(5 byte), 
    "A5_19_MENINGO_TETRA_ACWY" VARCHAR2(5 byte), 
    "MEQ1A_MENINGO_B_RECOMB_R_DATA" DATE, 
    CONSTRAINT "SPP_BENEFICIARIO_VACINA_PK" UNIQUE("ID") 
    USING INDEX  
    TABLESPACE "TSIND_SERIOUS" 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
    TABLESPACE "TS_SERIOUS" PCTFREE 10 PCTUSED 0 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 64K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 
    MONITORING;

*--------------------------------------------------------------------------------------------------*
* SEQUENCIA SEUNI.SPP_BENEFICIARIO_SEQ			                                                   *
*--------------------------------------------------------------------------------------------------*
CREATE SEQUENCE "SEUNI"."SPP_BENEFICIARIO_SEQ" INCREMENT BY 1 
    START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;

*--------------------------------------------------------------------------------------------------*
* SEQUENCIA SEUNI.SPP_BENEFICIARIO_CONSULTA_SEQ                                                    *
*--------------------------------------------------------------------------------------------------*
CREATE SEQUENCE "SEUNI"."SPP_BENEFICIARIO_CONSULTA_SEQ" INCREMENT
    BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;

*--------------------------------------------------------------------------------------------------*
* SEQUENCIA SEUNI.SPP_BENEFICIARIO_SEQ			                                                   *
*--------------------------------------------------------------------------------------------------*
CREATE SEQUENCE "SEUNI"."SPP_BENEFICIARIO_VACINA_SEQ" INCREMENT 
    BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;

*--------------------------------------------------------------------------------------------------*
* TRIGGER SEUNI.SPP_BENEFICIARIO_CONSULTA_ID                                                       *
*--------------------------------------------------------------------------------------------------*
CREATE OR REPLACE TRIGGER "SEUNI"."SPP_BENEFICIARIO_CONSULTA_ID" 
    BEFORE
INSERT ON "SPP_BENEFICIARIO_CONSULTA" FOR EACH ROW begin
select SPP_BENEFICIARIO_CONSULTA_SEQ.nextval into :new.id from dual;
end;

*--------------------------------------------------------------------------------------------------*
* TRIGGER SEUNI.SPP_BENEFICIARIO_VACINA_ID                                                         *
*--------------------------------------------------------------------------------------------------*
CREATE OR REPLACE TRIGGER "SEUNI"."SPP_BENEFICIARIO_VACINA_ID" 
    BEFORE
INSERT ON "SPP_BENEFICIARIO_VACINA" FOR EACH ROW begin
select SPP_BENEFICIARIO_VACINA_SEQ.nextval into :new.id from dual;
end;